### ISSUE TITLE
converting levels to VGLC encoding

### ISSUE THREAD

**Issue by famattsson** [TheHedgeify/DagstuhlGAN#6]
Hello!

For my purposes I need to convert the levels outputted (seemingly the output is a set of latent vectors, I assume I can simply use the levelfromlatentvector function to get the levels that would be outputted, please correct me if I am wrong) by the CMAMarioSolver class to a VGLC encoding, so that I can calculate some metrics from them. Is there any part of your codebase that could help with this.

**Comment by schrum2** [comment]
There could be, but I'm not certain. We convert the VGLC format into json in order to train the GAN. The GAN takes a latent vector and outputs the same json format. Then we convert that json format into a format that the Mario AI Framework can use. So, we never actually needed to convert that json format back to VGLC, and thus I'm not sure we ever bothered writing code to do that. However, you should be able to do static analysis on the json format just fine.

**Comment by famattsson** [comment]
I was able to get json levels from the evolutionary process and wrote my own code to convert into the VGLC format, thanks for the help!
