### ISSUE TITLE
Confused about training process

### ISSUE THREAD

**Issue by famattsson** [TheHedgeify/DagstuhlGAN#7]
Hi!

I have read through your paper multiple times now, and I don't quite understand what levels were used for training the GAN. Was it only level 1-1 from SMB or were there more? Also what do the 2x2, 3x3, and 4x4 on the wfc levels mean? For that matter what does the wfc abbreviation mean?

Thanks for any answer provided!

**Comment by schrum2** [comment]
The GECCO 2018 paper really did only use various slices from level 1-1, and that was it. However, immediately after, Vanessa verified that larger training sets could also be effective in her dissertation work. She split the levels into overworld, underworld, and athletic (the athletic levels were excluded because the platform movement mechanics are not supported by the Mario AI Framework). Vanessa's dissertation is here, but Mario is only a small part of it: 
[https://eldorado.tu-dortmund.de/handle/2003/37939](https://eldorado.tu-dortmund.de/handle/2003/37939)

Vanessa then had a publication at GECCO in 2019 that might explain what those WFC files are, but I'm not sure:
[https://arxiv.org/pdf/1905.05077.pdf](https://arxiv.org/pdf/1905.05077.pdf)

In later work that I did with Vanessa and others, we primarily used the training set for all the overworld levels.
[https://arxiv.org/abs/2004.00151](https://arxiv.org/abs/2004.00151)
[https://arxiv.org/abs/2004.01703](https://arxiv.org/abs/2004.01703)
